### ISSUE TITLE
Compilation errors in 2026.7.2

### ISSUE THREAD

**Issue by bleyton** [hencou/esphome_components#101]
I had this working fine a couple of months ago but after updating to 2026.7.2 I am getting the following errors:

Compiling .pioenvs/milight-hub/src/esphome/components/ota/ota_backend.cpp.o
In file included from .piolibdeps/milight-hub/RF24/RF24.h:18,
                 from src/esphome/components/mi/PL1167_nRF24.h:8,
                 from src/esphome/components/mi/mi.h:12,
                 from src/esphome/components/mi/mi.cpp:1:
.piolibdeps/milight-hub/RF24/RF24_config.h:190:26: error: expected ';' at end of member declaration
  190 |         #define printf_P Serial.printf
      |                          ^~~~~~
.piolibdeps/milight-hub/ESPAsyncWebServer/src/AsyncWebSocket.h:348:10: note: in expansion of macro 'printf_P'
  348 |   size_t printf_P(PGM_P formatP, ...) __attribute__((format(printf, 2, 3)));
      |          ^~~~~~~~
.piolibdeps/milight-hub/RF24/RF24_config.h:190:32: error: expected unqualified-id before '.' token
  190 |         #define printf_P Serial.printf
      |                                ^
.piolibdeps/milight-hub/ESPAsyncWebServer/src/AsyncWebSocket.h:348:10: note: in expansion of macro 'printf_P'
  348 |   size_t printf_P(PGM_P formatP, ...) __attribute__((format(printf, 2, 3)));
      |          ^~~~~~~~
.piolibdeps/milight-hub/RF24/RF24_config.h:190:26: error: expected ';' at end of member declaration
  190 |         #define printf_P Serial.printf
      |                          ^~~~~~
.piolibdeps/milight-hub/ESPAsyncWebServer/src/AsyncWebSocket.h:441:10: note: in expansion of macro 'printf_P'
  441 |   size_t printf_P(uint32_t id, PGM_P formatP, ...) __attribute__((format(printf, 3, 4)));
      |          ^~~~~~~~
.piolibdeps/milight-hub/RF24/RF24_config.h:190:32: error: expected unqualified-id before '.' token
  190 |         #define printf_P Serial.printf
      |                                ^
.piolibdeps/milight-hub/ESPAsyncWebServer/src/AsyncWebSocket.h:441:10: note: in expansion of macro 'printf_P'
  441 |   size_t printf_P(uint32_t id, PGM_P formatP, ...) __attribute__((format(printf, 3, 4)));
      |          ^~~~~~~~
